// This file is automatically generated from your CSS. Any edits will be overwritten.
export const content: string;
export const cover: string;
export const times: string;
export const buttons: string;
export const message: string;
