// This file is automatically generated from your CSS. Any edits will be overwritten.
export const root: string;
export const item: string;
export const grid: string;
export const tile: string;
export const cover: string;
